runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: F2

env_variables:
  CLOUD_SQL_USERNAME: 'sql-cloudlist'
  CLOUD_SQL_PASSWORD: 'cloudlist-esgi!'
  CLOUD_SQL_DATABASE: 'todos'
  CLOUD_SQL_CONNECTION_NAME: 'cloudlist-413718:europe-west2:sql-cloudlist'
  CLOUD_STORAGE_BUCKET_NAME: 'cloudlist-413718.appspot.com'
  AWS_LAMBDA_ENDPOINT: 'https://oypihpxobb.execute-api.eu-west-1.amazonaws.com/dev/'
  GOOGLE_APPLICATION_CREDENTIALS: 'cloudlist-413718-8af60a8713e5.json'


service_account: 'cloudlist-api@cloudlist-413718.iam.gserviceaccount.com'