runtime: python311
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
instance_class: F2

env_variables:
  CLOUD_SQL_USER: 'sql-cloudlist'
  CLOUD_SQL_PASSWORD: 'cloudlist-esgi!'
  CLOUD_SQL_DATABASE: 'todos'
  CLOUD_SQL_CONNECTION_NAME: 'cloudlist-413718:europe-west2:sql-cloudlist'
  CLOUD_STORAGE_BUCKET_NAME: 'cloudlist-413718.appspot.com'
